### ISSUE TITLE
Do you want the repository name plsql-utils?

### ISSUE THREAD

**Issue by eggplantpasta** [mortenbra/alexandria-plsql-utils#10]
Hi Morten,

Now that you're on Github I don't need my repository anymore https://github.com/eggplantpasta/plsql-utils. I'm about to delete it but since it has a shorter name than yours I thought I'd offer to transfer it to you first. If you want it (I imagine it's too late now). Thanks for all your awesome code.

Cheers, Brett.

**Comment by booyaa** [comment]
:+1:

**Comment by mortenbra** [comment]
Hi Brett, appreciate the offer, but I'm fine with keeping the more distinctive Alexandria name. Thanks for contributing! :-)

Regards, Morten
