### ISSUE TITLE
Q: jQGrid Integration Kit for PL/SQL and Apex

### ISSUE THREAD

**Issue by mongolu** [mortenbra/alexandria-plsql-utils#18]
Hello.

Is this still available to publc with BSD license?

I want to use it in an internal APEX project (i work in a distribution retail organization).

Can i use it freely ?

**Comment by mortenbra** [comment]
Hi, to clarify: The jQGrid Integration Kit for PL/SQL is not part of the Alexandria PL/SQL Library. It has not been ported over to GitHub and is still hosted at Google Code: https://code.google.com/p/jqgrid-for-plsql/

But yes, the jQGrid Integration Kit for PL/SQL is still available to the public with a BSD license, so you can use it freely.
