### ISSUE TITLE
about new features

### ISSUE THREAD

**Issue by kemal** [mortenbra/alexandria-plsql-utils#20]
Hello,

Im a plsql developer. I want to contribute this project.

Best Regards,
Kemal

**Comment by mbostwick** [comment]
Check out the issues.. or why not branch and do pull requests?.. Seems like opening an issue is not needed..

**Comment by mortenbra** [comment]
Hi Kemal, if you want to contribute, then fork the project, add your enhancements, and submit a pull request. Please also look at the guidelines in /doc/coding_standards.txt
