### ISSUE TITLE
Update xlsx_builder_pkg

### ISSUE THREAD

**Issue by eaolson** [mortenbra/alexandria-plsql-utils#31]
A colleague wanted to change the color of some text in an Excel file and I found that the xlsx_builder_pkg in this repo is out of date from the original author's (Anton Scheffer) version.

**Comment by eaolson** [comment]
Updated to the most recent version I could find, at https://technology.amis.nl/2011/02/19/create-an-excel-file-with-plsql/. Created pull request #32.

**Comment by mortenbra** [comment]
Merged.
