### ISSUE TITLE
Guys do you know any such library for ntlm token genration same like yours for postgres ? 

### ISSUE THREAD

**Issue by awesomehimanshu** [mortenbra/alexandria-plsql-utils#48]
I have used this in oracle can you tell me for postgres .

 l_ntlm_auth_str := plsql_utils.ntlm_http_pkg.begin_request(a_url, a_username, a_password);

I want to use same functionality in postgres.

**Comment by eaolson** [comment]
I don't know of any and a quick google search didn't turn up anything. You could use the code in this package to write your own version. But as this isn't a defect with plsql-utils, I'd suggest @mortenbra close this issue.

**Comment by awesomehimanshu** [comment]
Thanks
