### ISSUE TITLE
xlsx_builder_pkg should have invoker rights

### ISSUE THREAD

**Issue by eaolson** [mortenbra/alexandria-plsql-utils#52]
I was just using xlsx_builder_pkg for a project, and I think it should have invoker rights, mostly because of the query2sheet function. Without that setting, that function runs as whatever schema the package is installed in (in my case "alexandria"), so to access the tables used by the calling function, you have to grant select access to that schema. That seems like a security issue. I could install the package in whatever schema needs to use it, but I'm too lazy to figure out its dependencies and duplicating it all over the database seems inelegant.

**Comment by mortenbra** [comment]
Makes sense, tagging this as an enhancement request.

**Comment by commi235** [comment]
Take a look at my fork of that packag at https://github.com/commi235/xlsx_builder
I did some enhancements while developing a plugin.
Also someone added a more lightweight version of query2sheet.
