### ISSUE TITLE
There is no GOOGLE_CALENDAR_PKG

### ISSUE THREAD

**Issue by farhansuno** [mortenbra/alexandria-plsql-utils#9]
There is no GOOGLE_CALENDAR_PKG in the source code.

**Comment by maxhorizon** [comment]
Hi, any update on GOOGLE_CALENDAR_PKG? is it missing or still under development?

**Comment by mortenbra** [comment]
Check out the work done by Richard Martens on Google integration: https://github.com/smart4solutions/apex_oauth and http://2015.hroug.hr/eng/Program/Google-Apps-integration-in-Apex (downloadable presentation)
